# Generated by Django 3.2.4 on 2021-06-07 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faktura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Faktura',
            },
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=30)),
                ('nazwisko', models.CharField(max_length=30)),
                ('data_urodzenia', models.DateField()),
                ('email', models.CharField(max_length=30)),
                ('telefon', models.IntegerField()),
                ('login', models.CharField(max_length=30)),
                ('haslo', models.CharField(max_length=30)),
                ('miasto', models.CharField(max_length=30)),
                ('kod_pocztowy', models.CharField(max_length=6)),
                ('ulica', models.CharField(max_length=30)),
                ('lokal', models.IntegerField()),
                ('kraj', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Klient',
            },
        ),
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=30)),
                ('nazwisko', models.CharField(max_length=30)),
                ('telefon', models.IntegerField()),
                ('data_urodzenia', models.DateField()),
                ('data_zatrudnienia', models.DateField()),
                ('placa', models.FloatField()),
                ('miasto', models.CharField(max_length=30)),
                ('kod_pocztowy', models.CharField(max_length=6)),
                ('ulica', models.CharField(max_length=30)),
                ('lokal', models.IntegerField()),
                ('kraj', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Pracownik',
            },
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_produktu', models.CharField(max_length=80)),
                ('gatunek', models.CharField(
                    choices=[('Rock', 'Rock'), ('POP', 'Pop'), ('Klasyka', 'Muzyka Klasyczna'), ('Rap', 'Rap'),
                             ('Jazz', 'Jazz')], max_length=30)),
                ('opis_produktu', models.CharField(max_length=200)),
                ('dostepnosc',
                 models.CharField(choices=[('dostępny', 'Produkt dostępny'), ('niedostępny', 'Produkt niedostępny')],
                                  max_length=30)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('zdjecie', models.ImageField(upload_to='')),
                ('isRecommended', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Produkt',
            },
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_przyjecia', models.DateField()),
                ('status', models.CharField(max_length=30)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.klient')),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.pracownik')),
            ],
            options={
                'verbose_name_plural': 'Zamówienie',
            },
        ),
        migrations.CreateModel(
            name='Zamowiony_Przedmiot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.IntegerField()),
                ('cena', models.FloatField()),
                ('data_realizacji', models.DateField()),
                ('produkty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.produkt')),
                ('zamowienie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.zamowienie')),
            ],
            options={
                'verbose_name_plural': 'Zamówiony przedmiot',
            },
        ),
        migrations.CreateModel(
            name='Reklamacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('powod', models.CharField(max_length=30)),
                ('zamowienie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.zamowienie')),
            ],
            options={
                'verbose_name_plural': 'Reklamacja',
            },
        ),
        migrations.CreateModel(
            name='Platnosc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sposobPlatnosci', models.CharField(max_length=30)),
                ('status',
                 models.CharField(choices=[('ukończona', 'Płatność zrealizowana'), ('oczekuje', 'Płatność oczekuje')],
                                  max_length=30)),
                ('data', models.DateField()),
                ('faktura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.faktura')),
            ],
            options={
                'verbose_name_plural': 'Płatność',
            },
        ),
        migrations.CreateModel(
            name='Magazyn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.IntegerField()),
                ('miejsce', models.CharField(blank=True, max_length=50)),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.produkt')),
            ],
            options={
                'verbose_name_plural': 'Magazyn',
            },
        ),
        migrations.AddField(
            model_name='faktura',
            name='zamowienie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.zamowienie'),
        ),
        migrations.CreateModel(
            name='Dostawa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(max_length=30)),
                ('tracking_number', models.IntegerField()),
                ('data', models.DateField()),
                ('zamowienie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.zamowienie')),
            ],
            options={
                'verbose_name_plural': 'Dostawa',
            },
        ),
    ]
